Owner.create(owner_name: "原")
Owner.create(owner_name: "築城")
Owner.create(owner_name: "松田")
Owner.create(owner_name: "石井")
Owner.create(owner_name: "生崎")
Owner.create(owner_name: "渡邊")
Owner.create(owner_name: "諏訪")
Owner.create(owner_name: "葛葉")



Pet.create(owner_id: 1, kind: "カメ", name: "みどりがめ")
Pet.create(owner_id: 1, kind: "カメ", name: "ゼニガメ")
Pet.create(owner_id: 1, kind: "どじょう", name: "どじょちゃん")
Pet.create(owner_id: 2, kind: "トカゲ", name: "リザードン")
Pet.create(owner_id: 2, kind: "ネズミ", name: "ピカチュウ")
Pet.create(owner_id: 2, kind: "神", name: "アルセウス")
Pet.create(owner_id: 3, kind: "人外", name: "ハマーニャ")
Pet.create(owner_id: 3, kind: "魚人", name: "ラグラージ")
Pet.create(owner_id: 3, kind: "人外", name: "ルルーシュ")
Pet.create(owner_id: 4, kind: "インコ", name: "焼き鳥")
Pet.create(owner_id: 4, kind: "犬", name: "ワンコロ")
Pet.create(owner_id: 4, kind: "鹿", name: "ツノ")
Pet.create(owner_id: 5, kind: "フクロウ", name: "ヘドウィグ")
Pet.create(owner_id: 5, kind: "ヒッポグリフ", name: "ビックバーク")
Pet.create(owner_id: 6, kind: "ミニチュアホース", name: "にんじん丸")
Pet.create(owner_id: 6, kind: "カワウソ", name: "きゅうり")
Pet.create(owner_id: 7, kind: "妖怪", name: "ガンギマリ")
Pet.create(owner_id: 7, kind: "妖怪", name: "ハナシスギ")
Pet.create(owner_id: 7, kind: "妖怪", name: "ピュアヤンキー")
Pet.create(owner_id: 8, kind: "コモドドラゴン", name: "ぽこち")